; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
; App Information
AppName=AutoBrightness Engine
AppVersion=1.0
AppPublisher=Ayush Raj
DefaultDirName={autopf}\AutoBrightness
DefaultGroupName=AutoBrightness Engine
UninstallDisplayIcon={app}\logo.ico

; Installer Output Settings
OutputDir=userdocs:Inno Setup Examples Output
OutputBaseFilename=AutoBrightness_Setup
SetupIconFile=C:\auto-brightness-control\Installer_Build\logo.ico
Compression=lzma2
SolidCompression=yes

; Requires Admin rights to add to PATH and Program Files
PrivilegesRequired=admin

[Files]
; The actual files to package inside the installer
Source: "C:\auto-brightness-control\Installer_Build\AutoBrightness.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\auto-brightness-control\Installer_Build\logo.ico"; DestDir: "{app}"; Flags: ignoreversion

[Icons]
; Creates Desktop and Start Menu shortcuts
Name: "{autoprograms}\AutoBrightness Engine"; Filename: "{app}\AutoBrightness.exe"; IconFilename: "{app}\logo.ico"
Name: "{autodesktop}\AutoBrightness Engine"; Filename: "{app}\AutoBrightness.exe"; IconFilename: "{app}\logo.ico"; Tasks: desktopicon

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Registry]
; Environment PATH modification for the System
Root: HKLM; Subkey: "SYSTEM\CurrentControlSet\Control\Session Manager\Environment"; \
    ValueType: expandsz; ValueName: "Path"; ValueData: "{olddata};{app}"; \
    Check: NeedsAddPath(ExpandConstant('{app}'))

[Code]
// Helper function to check if the app directory is already in the PATH
function NeedsAddPath(Param: string): boolean;
var
  OrigPath: string;
begin
  if not RegQueryStringValue(HKEY_LOCAL_MACHINE,
    'SYSTEM\CurrentControlSet\Control\Session Manager\Environment',
    'Path', OrigPath)
  then begin
    Result := True;
    exit;
  end;
  // Look for the path with leading/trailing semicolons
  Result := Pos(';' + Param + ';', ';' + OrigPath + ';') = 0;
end;
